### PR TITLE
add Giraffe.ViewEngine.StrongName

### PR DESCRIPTION
**Pull request by kMutagene**
This PR adds `Giraffe.ViewEngine.StrongName` as a strong named assembly signed with the key in `src/Griaffe.ViewEngine.StrongName/key.snk`. 

See the discussion in #23. Build and release workflows would have to be adopted for also publishing this package. 

Usage is equal to `Giraffe.ViewEngine` other than referencing another nuget package:

image

### CODE REVIEW

**Comment by bradder555** [comment]
I don't know much about signing assemblies, but normally things are signed with a private key. I suspect this key shouldn't be here.

I'm thinking maybe we could store the key as a secret and create a github action to upload to nuget.

**Comment by bradder555** [comment]
also the existing actions fail in the pack step

```
   /home/runner/.dotnet/sdk/6.0.100/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(110,5): error MSB4018: System.ArgumentException: PackageVersion string specified '4574263522' is invalid. [/home/runner/work/Giraffe.ViewEngine/Giraffe.ViewEngine/src/Giraffe.ViewEngine/Giraffe.ViewEngine.fsproj]
   ```

**Comment by kMutagene** [comment]
https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

> If you are an open-source developer and you want the identity benefits of a strong-named assembly for better compatibility with .NET Framework, consider checking in the private key associated with an assembly to your source control system.

Signing an assembly is not a security feature, so I don't think keeping the key private is necessary when even the official docs recommend commiting it in source control.

**Comment by kMutagene** [comment]
> also the existing actions fail in the pack step

I did not touch the original Giraffe.ViewEngine.fsproj in this PR, so I suspect there is a general issue with how the project is packed now that there is more than one project. The version string for example is coming from `-p:PackageVersion=$GITHUB_RUN_ID` which i am pretty sure i had no influence on in any of the code added.

**Pull request closed without merging**
