### PR TITLE
Add .NET 8 target framework and use string interpolation

### PR DESCRIPTION
**Pull request by gumbarros**

### CODE REVIEW

**Comment by nojaf** [comment]
Hi @gumbarros, thank you for your interest in this project!
Do you have any specific use case in mind to use `net8.0` inside this library?
If not, adding that `net8.0` doesn't really do much when your own app is targeting the `net8.0` runtime.

**Comment by gumbarros** [comment]
Good morning!

Nah, just added .NET 8 to see if some new analyzer suggest something you can remove if you want :)

**Comment by nojaf** [comment]
That is an interesting sentence there. What did you expect to see from what kind of analyzer potentially?

**Comment by gumbarros** [comment]
> That is an interesting sentence there. What did you expect to see from what kind of analyzer potentially?

At least in C#, I found in my projects the following analyzers:
https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1859
https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1860

I don't have the info of new analyzers for F#

**Comment by nojaf** [comment]
Analyzers are not a thing in F#. It will potentially be on the roadmap for F# 9.

**Pull request closed without merging**
